// ---------------------------------------------------------------------------
// lib/history.ts — Client-side analysis history persistence
// ---------------------------------------------------------------------------
//
// Provides a lightweight history layer backed by localStorage so users can
// revisit past bill audits and insurance claim reviews without a backend.
//
// History entries are stored under the key `medguard_history` as a JSON
// array, with the most recent entry first. A rolling cap of 20 entries
// prevents unbounded storage growth.

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

/**
 * Represents a single entry in the analysis history.
 *
 * Persisted as part of a JSON array in localStorage under the key
 * `medguard_history`.
 */
interface HistoryEntry {
  /** Unique identifier for the entry (epoch timestamp as a string). */
  id: string;

  /** Whether this was a bill audit or an insurance appeal. */
  type: "bill" | "insurance";

  /** Name of the patient associated with this case. */
  patientName: string;

  /** Name of the insurance provider. */
  insurerName: string;

  /** The medical procedure or billing issue that was analysed. */
  procedureOrIssue: string;

  /** Human-readable date string for display purposes. */
  date: string;

  /** Estimated savings identified (in INR). */
  savings: number;

  /** Number of individual findings / anomalies detected. */
  findingsCount: number;

  /** Confidence percentage (0–100) for the analysis. */
  confidence: number;

  /** ISO 8601 timestamp of when the entry was originally created. */
  createdAt: string;
}

// ---------------------------------------------------------------------------
// Constants
// ---------------------------------------------------------------------------

/** localStorage key for the history array. */
const STORAGE_KEY = "medguard_history";

/** Maximum number of history entries to retain (oldest entries are evicted). */
const MAX_ENTRIES = 20;

// ---------------------------------------------------------------------------
// Public API
// ---------------------------------------------------------------------------

/**
 * Save a new analysis result to the local history.
 *
 * The entry is timestamped automatically (`id` and `createdAt` are
 * generated by this function). New entries are prepended so the most
 * recent analysis appears first when the history is displayed.
 *
 * When the history exceeds {@link MAX_ENTRIES}, the oldest entry is
 * removed to keep storage usage predictable.
 *
 * Safe to call during server-side rendering — the function body is
 * guarded with a `typeof window` check and will be a no-op on the server.
 *
 * @param entry - All history fields **except** `id` and `createdAt`,
 *                which are generated automatically.
 *
 * @example
 * ```ts
 * saveToHistory({
 *   type: "bill",
 *   patientName: "John Doe",
 *   insurerName: "UnitedHealthcare",
 *   procedureOrIssue: "MRI Lumbar Spine",
 *   date: "2026-04-25",
 *   savings: 2030,
 *   findingsCount: 2,
 *   confidence: 90,
 * });
 * ```
 */
export function saveToHistory(
  entry: Omit<HistoryEntry, "id" | "createdAt">
): void {
  // Guard: localStorage is only available in the browser.
  if (typeof window === "undefined") return;

  // Read the existing history array (or start a new one).
  const stored = localStorage.getItem(STORAGE_KEY);
  const history: HistoryEntry[] = stored ? JSON.parse(stored) : [];

  // Create the fully-formed entry with auto-generated metadata.
  const newEntry: HistoryEntry = {
    ...entry,
    id: Date.now().toString(),
    createdAt: new Date().toISOString(),
  };

  // Prepend so the newest entry appears first in the list.
  history.unshift(newEntry);

  // Evict the oldest entry if we've exceeded the maximum capacity.
  if (history.length > MAX_ENTRIES) {
    history.pop();
  }

  // Persist the updated array back to localStorage.
  localStorage.setItem(STORAGE_KEY, JSON.stringify(history));
}